server:
  port: ${PORT:0}

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061/eureka/

eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
