server:
  port: 8060

eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  routes:
    department:
      path: /books/**
      serviceId: book-service
    employee:
      path: /clients/**
      serviceId: client-service
    organization:
      path: /reservations/**
      serviceId: reservation-service