server:
  port: 8060

eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

zuul:
  routes:
    books:
      path: /books/**
      serviceId: book-service
    clients:
      path: /clients/**
      serviceId: client-service
    reservations:
      path: /reservations/**
      serviceId: reservation-service