server:
  port: 8082

eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:~/reservation-service-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use-sql-comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true